{
 "title": "Fraud Detection Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Suspicious Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fraud_alerts\")\r\n  |> range(start: -30d) // Adjust the time range as needed\r\n  |> filter(fn: (r) => r._measurement == \"fraud_transactions\")\r\n  |> filter(fn: (r) => r._field == \"amount\") // Focus on the \"amount\" field\r\n  |> group() // Remove grouping to count all transactions globally\r\n  |> count(column: \"_value\") // Count the number of rows\r\n  |> yield(name: \"transaction_count\")\r\n"
    }
   ]
  },
  {
   "title": "Total Amount of Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fraud_alerts\")\r\n  |> range(start: -30d) // Adjust the time range as needed\r\n  |> filter(fn: (r) => r._measurement == \"fraud_transactions\")\r\n  |> filter(fn: (r) => r._field == \"amount\") // Focus on the \"amount\" field\r\n  |> group() // Remove grouping by userId if you want a global total\r\n  |> sum(column: \"_value\") // Calculate the sum of transaction amounts\r\n  |> yield(name: \"total\")\r\n"
    }
   ]
  },
  {
   "title": "Last Transaction Amount",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fraud_alerts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Transaction Amount Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"fraud_alerts\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fraud_transactions\")\r\n  |> group(columns: [\"_measurement\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}